Use actual hostnames for blackbox configuration
open-io/ansible-role-openio-prometheus pull request #16
Opened 2019-03-12 02:34 UTC by jkasarherou

Blackbox checks were using hostname value from `ansible_hostname`, which was causing some invalid values:
`sds-1` (value in blackbox checks) vs `sds-1.novalocal` (value in prometheus)
Use `ansible_nodename` to get full hostname.

2019-03-12 10:45 UTC, vdombrovski requested changes
Please refactor commit title using these guidelines:

https://github.com/open-io/ansible-role-openio-skeleton/blob/master/CONTRIB.md

2019-03-12 10:57 UTC, jkasarherou commented
Are you kidding me??

2019-03-13 12:35 UTC, cdelgehier commented
The severity is missing, but ok

2019-03-13 12:35 UTC, merged

2019-03-14 02:15 UTC, jkasarherou commented
How would you decide the severity? The PR author itself? Seems inappropriate.