FEATURE(prometheus): Add healtchecks for keystone and galera
open-io/ansible-role-openio-prometheus pull request #48
Opened 2019-08-29 10:22 UTC by vdombrovski

##### SUMMARY

This adds additional checks for galera and keystone, aswell as a new
alert (IAM backend malfunction), indicating issues with the identity
management service.

Requires: https://github.com/open-io/ansible-role-openio-blackbox/pull/6

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

2019-08-30 01:31 UTC, loamhoof commented
:+1:

2019-08-30 02:10 UTC, jkasarherou approved these changes

2019-09-03 15:34 UTC, cdelgehier requested changes

2019-09-03 15:34 UTC, cdelgehier commented on docker-tests/test_addr.yml
> -      openio_repository_mirror_host: mirror2.openio.io
to change

2019-09-24 15:49 UTC, cdelgehier approved these changes

2019-09-24 15:49 UTC, merged