BUGFIX/MINOR(Monitoring): Fix fetch/load inventories when running in --check
open-io/ansible-role-openio-prometheus pull request #73
Opened 2020-05-19 12:26 UTC by dduportal

##### SUMMARY

- As an OpenIO administrator,
  When I run a "dry run" deployment  (e.g. adding the option `--check` to get a list of what will be done for the deployment)
  Then I does not want any error and a valid report
- This bugfix forces the task "Create temporary inventory directory" to be run even on `--check` mode, so the registered variable is always available.

 ##### IMPACT

- N.A.

 ##### ADDITIONAL INFORMATION

- Please note that the task "Fetch inventories" is now changed is Ansible detects a change, to help the dry run report to be more precise.

2020-05-19 21:50 UTC, cdelgehier commented on tasks/healthchecks.yml
> +  check_mode: no
use a "true" boolean
` check_mode: false`

2020-05-19 21:51 UTC, cdelgehier requested changes
`Fix fetch/load inventories when running in --check`

invalid commit message

2020-05-20 06:54 UTC, fatpat requested changes
same as @cdelgehier

2020-05-20 08:27 UTC, dduportal commented
Commit message + feedbacks applied. Waiting for the Travis CI to check if I broke something

2020-05-20 08:28 UTC, dduportal commented
(I was not able to run the test locally before pushing, so I'm relying on the Travis CI only)

2020-06-05 09:54 UTC, cdelgehier approved these changes

2020-06-23 10:26 UTC, merged